import React from 'react'
import PricingCard from '../Components/Pricing/PricingCard'
import HeroCardLayout from '../Components/Shipment/HeroCardLayout'
import Head from 'next/head'

const GetPricing = () => {
  return (
    <>
    <Head>
     <title>Create Next App</title>
     <meta name="description" content="Generated by create next app" />
     <link rel="icon" href="/favicon.ico" />
 </Head> 
<HeroCardLayout>
    <PricingCard/>
</HeroCardLayout>
  </>

  )
}

export default GetPricing