import Head from 'next/head'
import HeroCardLayout from '../Components/Shipment/HeroCardLayout'
import TrackingCard from '../Components/Track/TrackingCard'

const Track = () => {
  return (
    <>
    <Head>
     <title>Create Next App</title>
     <meta name="description" content="Generated by create next app" />
     <link rel="icon" href="/favicon.ico" />
 </Head> 
<HeroCardLayout>
    <TrackingCard/>
</HeroCardLayout>
  </>
  )
}

export default Track